INSERT INTO USUARIOS(nome, login, senha) VALUES('teste', 'teste@gmail.com', '$2a$10$Q4aa/OTpDIjvsua6rm0fqeTG4cU49S8DGCVjoKAn8k3n7DhUo0ozG');
INSERT INTO USUARIOS(nome, login, senha) VALUES('user', 'user@gmail.com', '$2a$10$Q4aa/OTpDIjvsua6rm0fqeTG4cU49S8DGCVjoKAn8k3n7DhUo0ozG');

INSERT INTO CLIENTES(ID, NOME, ENDERECO, EMAIL, CNPJ) VALUES (1,'teste','RUA INGLATERRA','teste@gmail.com','098983512');

INSERT INTO CLIENTES(ID, NOME, ENDERECO, EMAIL, CNPJ) VALUES (2,'user','RUA TOKYO','user@gmail.com','4454666656');



INSERT INTO CHAMADOS(ID, ASSUNTO, STATUS, COMPLEMENTO) VALUES (1,'SUPORTE','PROGRESSO','CONSERTAR TELEFONE');
INSERT INTO CHAMADOS(ID, ASSUNTO, STATUS, COMPLEMENTO) VALUES (2,'FINANCEIRO','ABERTO','SALARIO DOS TERCEIRIZADOS');
INSERT INTO CHAMADOS(ID, ASSUNTO, STATUS, COMPLEMENTO) VALUES (3,'SUPORTE','ATENDIDO','SENHA DE ADM');
INSERT INTO CHAMADOS(ID, ASSUNTO, STATUS, COMPLEMENTO) VALUES (4,'FINANCEIRO','PROGRESSO','LICENCA SEMANAL');
INSERT INTO CHAMADOS(ID, ASSUNTO, STATUS, COMPLEMENTO) VALUES (5,'VISITA','ABERTO','AUDITORIA DAS INSTALACOES');
